version: "3.9"

services:
  vnc:
    build:
      context: .
      dockerfile: docker/vnc.Dockerfile
    image: shmocz/vnc:latest
    command: sh -c 'Xvnc :1 -depth 24 -geometry $$RESOLUTION -br -rfbport=5901 -SecurityTypes None -AcceptSetDesktopSize=off'
    environment:
      RESOLUTION: "1280x1024"
    ports:
      - "6081:6081" # novnc
      - "12001:5901" # vnc
      - "50000:50000" # tunnel
      - "14521:14521" # ra2yrcpp
      - "12340:12340" # debugger
  novnc:
    image: shmocz/vnc:latest
    network_mode: service:vnc
    user: root
    command: /utils/novnc_proxy --vnc localhost:5901 --listen 6081
  wm:
    image: shmocz/vnc:latest
    command: sh -c 'exec openbox-session'
    depends_on:
      - vnc
    env_file:
      - integration.env
    network_mode: service:vnc
  builder:
    image: shmocz/ra2yrcpp:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/home/user/project
      - ./wine-dir:/home/user/.wine
    user: "${UID}:${UID}"
    env_file:
      - integration.env
    command: "${COMMAND}"
    working_dir: /home/user/project
  clang-cl:
    image: shmocz/clang-cl:latest
    build:
      context: .
      dockerfile: docker/clang-cl-msvc.Dockerfile
    volumes:
      - .:/home/user/project
      - gamedata:/home/user/RA2
      - ./.wine-clang:/home/user/.wine
    command: "${COMMAND}"
    working_dir: /home/user/project
    # to get debug dlls
    env_file:
      - integration.env
    user: "${UID}:${UID}"
  tunnel:
    build:
      context: .
      dockerfile: docker/tunnel.Dockerfile
    image: shmocz/pycncnettunnel:latest
    stop_signal: SIGKILL
    network_mode: service:vnc
  pyra2yr:
    build:
      context: .
      dockerfile: docker/pyra2yr.Dockerfile
    image: shmocz/pyra2yr:latest
    volumes:
      - .:/home/user/project
    command: |
      sh -c '
      if [ ! -d .venv ]; then
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m pip install -r requirements.txt -e .
      else
        set -e
        . .venv/bin/activate
        set +e
        python3 -m pip install -r requirements.txt -e .
      fi
      ${COMMAND_PYRA2YR}'
    stop_signal: SIGKILL
    working_dir: /home/user/project/pyra2yr
    tty: true
    network_mode: service:vnc

volumes:
  gamedata:
    driver: local
    driver_opts:
      type: none
      device: /home/user/project/maingame # path to CnCNet files
      o: bind
