version: "3.9"
services:
  game-0:
    stop_signal: SIGKILL
    image: shmocz/ra2yrcpp:latest
    depends_on:
      - wm
    user: "${UID}:${GID}"
    working_dir: /home/user/project
    volumes:
      - gamedata:/home/user/RA2
      - ./wine-dir:/home/user/.wine
      - .:/home/user/project
    command: "${COMMAND}"
    env_file:
      - integration.env
    environment:
      PLAYER_ID: player_0
      RA2YRCPP_PORT: 14521
    network_mode: service:vnc
  game-1:
    stop_signal: SIGKILL
    image: shmocz/ra2yrcpp:latest
    depends_on:
      - wm
    user: "${UID}:${GID}"
    working_dir: /home/user/project
    volumes:
      - gamedata:/home/user/RA2
      - ./wine-dir:/home/user/.wine
      - .:/home/user/project
    command: "${COMMAND}"
    env_file:
      - integration.env
    environment:
      PLAYER_ID: player_1
      RA2YRCPP_PORT: 14522
    network_mode: service:vnc
