version: "3.9"

services:
  game-0:
    cap_add:
      - SYS_PTRACE
    command: "${COMMAND}"
    depends_on:
      - wm
    env_file:
      - integration.env
    image: shmocz/ra2yrcpp:latest
    network_mode: service:vnc
    stop_signal: SIGKILL
    volumes:
      - .:/home/user/project
      - gamedata:/home/user/RA2
      - ./.wine-dir:/home/user/.wine
    working_dir: /home/user/project
