version: "3.9"

services:
  builder:
    image: shmocz/ra2yrcpp:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/home/user/project
      - ./wine-dir:/home/user/.wine
    user: "${UID}:${UID}"
    command: "${COMMAND}"
    working_dir: /home/user/project
  clang-cl:
    image: shmocz/clang-cl:latest
    build:
      context: .
      dockerfile: docker/clang-cl-msvc.Dockerfile
    volumes:
      - .:/home/user/project
      - ./.wine-clang:/home/user/.wine
    command: "${COMMAND}"
    working_dir: /home/user/project
    user: "${UID}:${UID}"
