set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_CXX_STANDARD 17)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)
set(ROOT_WINDOWS /home/user/i686-w64-mingw32)
set(ROOT_LINUX ${USER_ENVS}/linux_x86_64)
set(CMAKE_SYSROOT /usr/${TOOLCHAIN_PREFIX})
set(INCLUDE_CXX, /usr/lib/gcc/i686-w64-mingw32/10-posix/include/c++)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
set(PROTOC_PATH ${ROOT_LINUX}/bin/protoc)
set(PROTOBUF_INCLUDE_DIR ${CMAKE_SYSROOT}/include)

set(CMAKE_FIND_ROOT_PATH ${ROOT_WINDOWS};${ROOT_LINUX};${INCLUDE_CXX})
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/lib/gcc/i686-w64-mingw32/10-posix/include)

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)