set(CMAKE_SYSTEM_NAME Windows)
set(HOST_ARCH i686)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)
set(CMAKE_SYSROOT /usr/${TOOLCHAIN_PREFIX})

if(DEFINED ENV{TC_VERSION})
    set(TC_VERSION "$ENV{TC_VERSION}")
else()
    file(GLOB TC_PATHL "/usr/lib/gcc/${TOOLCHAIN_PREFIX}/*")
    list(GET TC_PATHL 0 TC_PATH)
    cmake_path(GET TC_PATH FILENAME TC_VERSION)
endif()

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++ CACHE FILEPATH "")
set(CMAKE_CXX_STANDARD 17 CACHE STRING "")
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/lib/gcc/${TOOLCHAIN_PREFIX}/${TC_VERSION}/include)

# Need these to find headers etc.
# TODO: copy the native protoc executable to pkg
if(DEFINED ENV{FIND_ROOT_PATH})
    set(CMAKE_FIND_ROOT_PATH "$ENV{FIND_ROOT_PATH}")
endif()

if(DEFINED ENV{PROTOC_PATH})
    set(PROTOC_PATH "$ENV{PROTOC_PATH}")
endif()

if(DEFINED ENV{PROTO_LIB})
    set(PROTO_LIB "$ENV{PROTO_LIB}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ALWAYS)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Enable these to strip symbols
# set(CMAKE_SHARED_LINKER_FLAGS -s)
# set(CMAKE_EXE_LINKER_FLAGS -s)

# set(RA2YRCPP_BUILD_MAIN_DLL ON CACHE BOOL "")
# set(RA2YRCPP_BUILD_TESTS ON CACHE BOOL "")