set(CMAKE_SYSTEM_NAME Windows)
set(HOST_ARCH i686)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)
set(GCC_VERSION 12)
set(CMAKE_CXX_STANDARD 17)
set(ROOT_LINUX ${USER_ENVS}/linux_x86_64)
set(CMAKE_SYSROOT /usr/${TOOLCHAIN_PREFIX})
set(INCLUDE_CXX, /usr/lib/gcc/${TOOLCHAIN_PREFIX}/${GCC_VERSION}-posix/include/c++)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
set(PROTOC_PATH ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/bin/protoc)

set(CMAKE_FIND_ROOT_PATH ${ROOT_LINUX};${INCLUDE_CXX})
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/lib/gcc/${TOOLCHAIN_PREFIX}/${GCC_VERSION}-posix/include)

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)